# Generated by Django 3.1.7 on 2021-02-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digita',
            new_name='digital',
        ),
    ]
