# Generated by Django 3.1.7 on 2021-02-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210224_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_1', models.CharField(max_length=3000)),
                ('image_1', models.ImageField(null=True, upload_to='')),
                ('desc_2', models.CharField(max_length=3000)),
                ('image_2', models.ImageField(null=True, upload_to='')),
                ('desc_3', models.CharField(max_length=3000)),
                ('image_3', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
