# Generated by Django 3.1.7 on 2021-02-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='topc_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='topc_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='topc_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='desc_1',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='desc_2',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='desc_3',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_1',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_2',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_3',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
