# Generated by Django 3.1.7 on 2021-02-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210226_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
