# Generated by Django 3.1.7 on 2021-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_description_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='desc_4',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='image_4',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='topc_4',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
