# Generated by Django 3.1.7 on 2021-02-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210226_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='desc_2',
        ),
        migrations.RemoveField(
            model_name='description',
            name='desc_3',
        ),
        migrations.RemoveField(
            model_name='description',
            name='desc_4',
        ),
        migrations.RemoveField(
            model_name='description',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='description',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='description',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='description',
            name='topc_2',
        ),
        migrations.RemoveField(
            model_name='description',
            name='topc_3',
        ),
        migrations.RemoveField(
            model_name='description',
            name='topc_4',
        ),
    ]
