# Generated by Django 3.1.7 on 2021-02-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210226_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='image',
        ),
    ]
