# Generated by Django 3.1.7 on 2021-02-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Deskripsi dari produk'),
        ),
    ]
