# Generated by Django 3.1.7 on 2021-02-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_description_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Deskripsi dari produk'),
        ),
    ]
