# Generated by Django 3.1.7 on 2021-02-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210226_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.description', verbose_name='Deskripsi produk'),
        ),
    ]
